### ISSUE TITLE
А в чём смысл вводить наследников Hex и Bin от Int?

### ISSUE THREAD

**Issue by Mazdaywik** [ponyatov/pyF#1]
Представление целого числа — в виде двоичного, восьмеричного, десятичного или шестнадцатеричного — это деталь лексического анализа. На стадии синтаксического анализа, а уж тем более на стадии выполнения она нафиг не нужна.

Чем должно отличаться сложение десятичных чисел от сложения двоичных? Неужели тем, что при выводе суммы двоичных чисел она должна отображаться как двоичное число?

**Comment by ponyatov** [comment]
**hex** машинное целое, размер слова в степенях двойки

**bin** битовое поле, произвольное число бит (планируется для декодирования форматов, бинарные поля в упакованных структурах)

на **int** никто размерность не накладывает, втч arbitrary precision (libgmp)

как то так

**Comment by Mazdaywik** [comment]
Просто из названия и реализации это не очевидно — кажется, что это просто разные способы записи целого числа. Во всех известных мне языках программирования тип целого числа не определяется его системой счисления, в том же Си — `0x3F`, `63` и `077` определяют одно и то же число типа `int`. Тип литерала явно указывается суффиксами: `0x3FL` (`long int`), `077U` (`unsigned int`) и `63UL` (`unsigned long int`).


А почему тогда машинное слово и битовая строка — наследники от целого, а не от числа или примитива?

А сложение битовых строк можно понимать и как конкатенацию. Для сложения их целочисленных значений разумно сначала приводить их к числу.
